// genmapcache turns a directory of circuits into a compiled-in longfellow.MapCache.
//
// Identifying a circuit costs about 1.2 seconds: circuit_id decompresses it,
// parses it into its two circuits, and hashes their ids. An application that
// bundles eight circuits and does that at every launch pays ten seconds of
// startup for an answer that cannot change, because the files are fixed at
// build time. Measured in the Yivi app on 2026-09-23, that cost showed up as a
// frozen main thread and Android's ANR watchdog sampling it twice.
//
// So this runs the identification ONCE, here, and emits the result as Go
// source. Open then consults the map instead of identifying, and a launch costs
// a SHA-256 over each file's compressed bytes.
//
// Why generated rather than written by hand, and why the filenames are never
// read: a circuit's claimed identity has to be checked against its content, or
// AcceptedCircuits is comparing labels rather than circuits. Multipaz's
// addCircuit parses the hash out of the filename with nothing verifying that
// the two correspond. This does the opposite — the name is used only to warn
// when it disagrees with what the bytes actually are.
//
// Needs cgo and the native library, so it runs in the build container.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing/fstest"

	"github.com/privacybydesign/longfellow-go/longfellow"
)

func main() {
	dir := flag.String("dir", "", "directory of circuit files")
	out := flag.String("out", "", "Go file to write")
	pkg := flag.String("package", "", "package clause for the generated file")
	tag := flag.String("tag", "longfellow", "build tag the generated file carries")
	symbol := flag.String("symbol", "bundledCircuits", "name of the generated MapCache variable")
	flag.Parse()

	if *dir == "" || *out == "" || *pkg == "" {
		fmt.Fprintln(os.Stderr, "usage: genmapcache -dir D -out F -package P [-tag T] [-symbol S]")
		os.Exit(2)
	}
	if err := run(*dir, *out, *pkg, *tag, *symbol); err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: %v\n", err)
		os.Exit(1)
	}
}

type entry struct{ name, digest, id string }

func run(dir, out, pkg, tag, symbol string) error {
	names, err := circuitFiles(dir)
	if err != nil {
		return err
	}
	if len(names) == 0 {
		return fmt.Errorf("no circuit files in %s", dir)
	}

	var entries []entry
	for _, name := range names {
		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return err
		}

		// One file at a time, so the identity that comes back belongs to THIS
		// file. Open fails on anything it cannot identify, so reaching the end
		// means every file is a circuit this build of the library knows.
		system, err := longfellow.Open(fstest.MapFS{"circuit": &fstest.MapFile{Data: content}})
		if err != nil {
			return fmt.Errorf("identify %s: %w", name, err)
		}
		circuits := system.Circuits()
		if len(circuits) != 1 {
			system.Close()
			return fmt.Errorf("identify %s: got %d circuits, want 1", name, len(circuits))
		}
		id := circuits[0].Hash
		system.Close()

		digest := longfellow.FileDigest(content)
		entries = append(entries, entry{name: name, digest: digest, id: id})

		status := "ok"
		if claimed := hashFromName(name); claimed == "" {
			status = "name carries no hash to compare against"
		} else if claimed != id {
			status = "MISMATCH: the name claims " + claimed
		}
		fmt.Printf("  %s\n      digest %s\n      id     %s  (%s)\n", name, digest, id, status)
		if strings.HasPrefix(status, "MISMATCH") {
			return fmt.Errorf("%s is not the circuit its name claims", name)
		}
	}

	return write(out, pkg, tag, symbol, entries)
}

// circuitFiles lists the files to identify, skipping the ones Open also skips
// by name so the two agree about what is and is not a circuit.
func circuitFiles(dir string) ([]string, error) {
	listing, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, item := range listing {
		name := item.Name()
		if item.IsDir() || name == "README.md" || strings.HasPrefix(name, ".") {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

// hashFromName returns the hash Multipaz's filename convention claims, or "".
func hashFromName(name string) string {
	parts := strings.Split(name, "_")
	if len(parts) != 5 || len(parts[4]) != 64 {
		return ""
	}
	return parts[4]
}

func write(out, pkg, tag, symbol string, entries []entry) error {
	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", tag)
	fmt.Fprintf(&b, "// Code generated by longfellow-go/cmd/genmapcache. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Each entry maps a circuit file's SHA-256 to the identity longfellow's\n")
	fmt.Fprintf(&b, "// circuit_id computed from its content. Regenerate whenever the bundled\n")
	fmt.Fprintf(&b, "// circuits change; a stale or wrong entry costs a slow load and nothing\n")
	fmt.Fprintf(&b, "// else, because identify() falls back to the real thing when a cached id\n")
	fmt.Fprintf(&b, "// does not name a circuit this build knows.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import \"github.com/privacybydesign/longfellow-go/longfellow\"\n\n")
	fmt.Fprintf(&b, "var %s = longfellow.MapCache{\n", symbol)
	for _, e := range entries {
		fmt.Fprintf(&b, "\t// %s\n", e.name)
		fmt.Fprintf(&b, "\t%q: %q,\n", e.digest, e.id)
	}
	fmt.Fprintf(&b, "}\n")

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("\nwrote %s (%d circuits)\n", out, len(entries))
	return nil
}
